FROM debian:bookworm-slim
ADD aptly-publish /usr/bin/
ARG APTLY_SERVER
ARG APTLY_USER
ARG APTLY_PASSWORD
ENV APTLY_SERVER=${APTLY_SERVER}
ENV APTLY_USER=${APTLY_USER}
ENV APTLY_PASSWORD=${APTLY_PASSWORD}
ENTRYPOINT ["aptly-publish"]
